preset_color_schemes:
  salty:
    name: "Salty"
    author: "Salt <saltchang.tw@gmail.com>"
    font_face: "PingFangTC-Regular,HanaMinB"
    font_point: 20
    font_weight: 500
    horizontal: false
    label_font_face: "Menlo"
    label_font_point: 16
    back_color: "0x181A12"
    text_color: "0x7BC0E5"
    hilited_text_color: "0x6F59EF"
    hilited_back_color: "0x7BC0E5"
    hilited_candidate_text_color: "0xDBD5C1"
    hilited_candidate_back_color: "0x0070BA"
    hilited_candidate_label_color: "0xDBD5C1"
    hilited_comment_text_color: "0xDBD5C1"
    candidate_text_color: "0x7BC0E5"
    label_color: "0x7BC0E5"
    comment_text_color: "0x7BC0E5"
show_notifications_when: appropriate
style:
  border_height: 0
  border_width: 0
  color_scheme: salty
  comment_font_point: 18
  corner_radius: 10
  font_face: "Lucida Grande"
  font_point: 21
  hilited_corner_radius: 0
  inline_preedit: true
  label_font_point: 18
  line_spacing: 5
  spacing: 10
  text_orientation: horizontal
